/// <reference types="vite/client" />
// ─── src/services/sheetsService.ts ──────────────────────────────────────────
/**
 * @fileoverview Google Sheets Integration Service for Booking System.
 * @description Appends booking records to a Google Sheet via Google Apps Script
 *              Webhook. This provides a free, serverless database for tracking
 *              all appointment requests with automatic timestamping and status management.
 *
 * @architecture
 * - Uses Google Apps Script Web App as a REST endpoint
 * - Sends data via POST with mode: 'no-cors' (required for Google Apps Script)
 * - Opaque response handling (cannot read response body due to CORS)
 * - Fault-tolerant: gracefully skips if webhook URL is not configured
 *
 * @author Mohammad Hossein (Senior Frontend Engineer)
 * @version 1.0.0
 * @since 2026-09-10
 */

import { IBookingRequest, IBookingResponse } from '../types/booking';

// ─── Constants & Configuration ──────────────────────────────────────────────

/**
 * @constant WEBHOOK_URL
 * @description Google Apps Script Web App URL for appending data to Sheets
 */
const WEBHOOK_URL = import.meta.env.VITE_SHEETS_WEBHOOK_URL;

// ─── Type Definitions ───────────────────────────────────────────────────────

/**
 * @interface ISheetsPayload
 * @description Structured payload sent to Google Apps Script
 */
interface ISheetsPayload {
    /** Unique booking tracking ID (e.g., "MOM-4829") */
    bookingId: string;
    /** Patient's full name */
    fullName: string;
    /** Iranian mobile number */
    phone: string;
    /** Optional email address */
    email: string;
    /** Appointment date (YYYY-MM-DD format) */
    date: string;
    /** Appointment time (HH:mm format) */
    time: string;
    /** Type of visit: "حضوری" or "آنلاین" */
    visitType: string;
    /** Insurance provider name or "آزاد" */
    insurance: string;
    /** Patient's reason for visit or notes */
    description: string;
    /** Initial status: always "pending" for new bookings */
    status: 'pending' | 'confirmed' | 'cancelled' | 'completed';
    /** ISO 8601 timestamp of booking creation */
    createdAt: string;
}

// ─── Helper Functions ───────────────────────────────────────────────────────

/**
 * @function buildSheetsPayload
 * @description Constructs the payload object for Google Sheets
 * @param data - The validated booking request
 * @param bookingId - The unique tracking ID generated by bookingService
 * @returns Structured payload ready for API submission
 */
const buildSheetsPayload = (
    data: IBookingRequest,
    bookingId: string
): ISheetsPayload => {
    return {
        bookingId,
        fullName: data.fullName.trim(),
        phone: data.phone.trim(),
        email: data.email?.trim() || '',
        date: data.date,
        time: data.time,
        visitType: data.visitType,
        insurance: data.insurance?.trim() || 'آزاد',
        description: data.description?.trim() || '',
        status: 'pending',
        createdAt: new Date().toISOString(),
    };
};

// ─── Service Implementation ─────────────────────────────────────────────────

/**
 * @function sendToGoogleSheets
 * @description Appends a booking record to Google Sheets via Apps Script Webhook.
 *
 * @implementation_notes
 * - Uses fetch with mode: 'no-cors' because Google Apps Script Web Apps
 *   do not support CORS headers properly
 * - Opaque response means we cannot read the response body, but we can
 *   detect network errors via try/catch
 * - Returns success: true even if webhook is not configured (graceful degradation)
 *
 * @param data - The validated booking request payload
 * @param bookingId - The unique tracking ID (e.g., "MOM-4829")
 * @returns A promise resolving to the standardized booking response
 *
 * @example
 * ```typescript
 * const response = await sendToGoogleSheets(bookingData, 'MOM-4829');
 * if (response.success) {
 *   console.log('Booking saved to Google Sheets');
 * }
 * ```
 */
export const sendToGoogleSheets = async (
    data: IBookingRequest,
    bookingId: string
): Promise<IBookingResponse> => {
    // ─── Guard Clause: Skip gracefully if webhook is not configured ─────────
    if (!WEBHOOK_URL) {
        console.warn(
            '[SheetsService] VITE_SHEETS_WEBHOOK_URL not configured. Skipping Google Sheets sync.'
        );
        return {
            success: true, // Return true to not block the main booking flow
            message: 'ذخیره در گوگل شیت (غیرفعال — وب‌هوک تنظیم نشده است)',
        };
    }

    try {
        // ─── Build Payload ────────────────────────────────────────────────────
        const payload = buildSheetsPayload(data, bookingId);
        console.log('[SheetsService] 📝 Preparing payload for Google Sheets:', payload);

        // ─── API Request ──────────────────────────────────────────────────────
        // Note: mode: 'no-cors' is REQUIRED for Google Apps Script Web Apps
        // This means we get an opaque response and cannot read the response body
        const response = await fetch(WEBHOOK_URL, {
            method: 'POST',
            mode: 'no-cors',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(payload),
        });

        // ─── Response Handling ────────────────────────────────────────────────
        // With mode: 'no-cors', response.type will be 'opaque' and response.ok
        // will be false, but the request was actually sent successfully.
        // We assume success if no exception was thrown.
        console.log('[SheetsService] ✅ Request sent to Google Sheets (opaque response).');

        return {
            success: true,
            message: 'نوبت با موفقیت در گوگل شیت ثبت شد',
        };
    } catch (error) {
        // ─── Error Handling ───────────────────────────────────────────────────
        // Network errors, invalid URL, or CORS issues will be caught here
        console.error('[SheetsService] ❌ Exception while sending to Google Sheets:', error);

        return {
            success: false,
            message: 'خطا در ذخیره نوبت در گوگل شیت. لطفاً با پشتیبانی تماس بگیرید.',
        };
    }
};

// ─── Default Export ─────────────────────────────────────────────────────────
export default sendToGoogleSheets;

// ─── End of File ────────────────────────────────────────────────────────────
